//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorHarness.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorHarness.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis expected.
        /// </summary>
        internal static string Calculator_ErrClosingParenExpected {
            get {
                return ResourceManager.GetString("Calculator_ErrClosingParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell range must be within one column or within one row.
        /// </summary>
        internal static string Calculator_ErrInvalidCellRange {
            get {
                return ResourceManager.GetString("Calculator_ErrInvalidCellRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operand.
        /// </summary>
        internal static string Calculator_ErrInvalidOperand {
            get {
                return ResourceManager.GetString("Calculator_ErrInvalidOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand contains multiple decimal points.
        /// </summary>
        internal static string Calculator_ErrMultipleDecimalPoints {
            get {
                return ResourceManager.GetString("Calculator_ErrMultipleDecimalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand expected.
        /// </summary>
        internal static string Calculator_ErrOperandExpected {
            get {
                return ResourceManager.GetString("Calculator_ErrOperandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator expected.
        /// </summary>
        internal static string Calculator_ErrOperatorExpected {
            get {
                return ResourceManager.GetString("Calculator_ErrOperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined function &quot;{0}&quot;.
        /// </summary>
        internal static string Calculator_ErrUndefinedFunction {
            get {
                return ResourceManager.GetString("Calculator_ErrUndefinedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined symbol &quot;{0}&quot;.
        /// </summary>
        internal static string Calculator_ErrUndefinedSymbol {
            get {
                return ResourceManager.GetString("Calculator_ErrUndefinedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character encountered &apos;{0}&apos;.
        /// </summary>
        internal static string Calculator_ErrUnexpectedCharacter {
            get {
                return ResourceManager.GetString("Calculator_ErrUnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis without matching open parenthesis.
        /// </summary>
        internal static string Calculator_ErrUnmatchedClosingParen {
            get {
                return ResourceManager.GetString("Calculator_ErrUnmatchedClosingParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of function parameters.
        /// </summary>
        internal static string Calculator_ErrWrongParamCount {
            get {
                return ResourceManager.GetString("Calculator_ErrWrongParamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (column {1}).
        /// </summary>
        internal static string FormulaCommand_Exception {
            get {
                return ResourceManager.GetString("FormulaCommand_Exception", resourceCulture);
            }
        }
    }
}
